{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homer.fullname" . }}-grafana
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  serviceName: {{ include "homer.fullname" . }}-grafana
  replicas: 1
  selector:
    matchLabels:
      {{- include "homer.labels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "homer.labels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      securityContext:
          runAsUser: 472
          fsGroup: 472
      containers:
        - image: {{ .Values.grafana.image }}
          name: grafana
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-claim
            - mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              name: grafana-provisioning
              subPath: datasource.yaml
            - mountPath: /etc/grafana/provisioning/dashboards/default.yaml
              name: grafana-provisioning
              subPath: default-dashboard.yaml
            - mountPath: /var/lib/grafana/dashboards/jambonz-dashboard.json
              name: grafana-provisioning
              subPath: jambonz-dashboard.json
            - mountPath: /var/lib/grafana/dashboards/jambonz-heplify.json
              name: grafana-provisioning
              subPath: jambonz-heplify.json
      restartPolicy: Always
      volumes:
      - name: grafana-provisioning
        configMap:
          name: {{ include "homer.fullname" . }}-grafana
          items:
          - key: datasource.yaml
            path: datasource.yaml
          - key: default-dashboard.yaml
            path: default-dashboard.yaml
          - key: jambonz-dashboard.json
            path: jambonz-dashboard.json
          - key: jambonz-heplify.json
            path: jambonz-heplify.json
  volumeClaimTemplates:
  - metadata:
      name: grafana-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.grafana.storage }}
{{- end }}
