apiVersion: v1
kind: Service
metadata:
  labels:
    app: heplify-server
{{ include "common.labels" . | indent 4 }}
{{- with .Values.heplifyServer.service.annotations }}
  annotations:
    {{- . | indent 4 }}
{{- end }}
  name: heplify-server
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  ports:
    - name: "heplify-server"
      port: 9060
      targetPort: 9060
      protocol: UDP
    - name: "stats-scraper"
      port: 9096
      targetPort: 9096
      protocol: TCP
  selector:
    app: heplify-server
{{- if .Values.heplifyServer.service.clusterIP }}
  clusterIP: None
{{- else }}
  type: {{ .Values.heplifyServer.service.type }}
{{- end }}
{{- if .Values.heplifyServer.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.heplifyServer.service.loadBalancerIP }}
{{- end }}
