apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer.fullname" . }}-influxdb
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
spec:
  ports:
    - name: "influxdb"
      port: 8086
      targetPort: 8086
  selector:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
  clusterIP: None
