apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homer.fullname" . }}-influxdb
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
spec:
  serviceName: {{ include "homer.fullname" . }}-influxdb
  replicas: 1
  selector:
    matchLabels:
      {{- include "homer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: influxdb
  template:
    metadata:
      labels:
        {{- include "homer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: influxdb
    spec:
      containers:
        - image: {{ .Values.influxdb.image }}
          name: influxdb
          env:
            - name: {{ .Values.influxdb.loglevel| quote }}
              value: info
          ports:
            - containerPort: 8086
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-claim
          livenessProbe:
            httpGet:
              path: /ping
              port: 8086
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ping
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5        
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: influxdb-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.influxdb.storage }}
