{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer.fullname" . }}-postgres
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    {{- include "homer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  clusterIP: None
{{- end }}
