{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homer.fullname" . }}-postgres
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "homer.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "homer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "homer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - image: {{ .Values.postgres.image }}
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: homerSeven
            - name: POSTGRES_USER
              value: root
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-claim
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: postgres-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}
{{- end }}
