apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homer.fullname" . }}-telegraf
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
spec:
  serviceName: {{ include "homer.fullname" . }}-telegraf
  replicas: 1
  selector:
    matchLabels:
      {{- include "homer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: telegraf
  template:
    metadata:
      labels:
        {{- include "homer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: telegraf
    spec:
      containers:
        - image: {{ .Values.telegraf.image }}
          name: telegraf
          ports:
            - containerPort: 8125
          resources: {}
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: config
              subPath: telegraf.conf
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: {{ include "homer.fullname" . }}-telegraf
          items:
          - key: telegraf.conf
            path: telegraf.conf
