apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer.fullname" . }}-telegraf
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
spec:
  ports:
    - name: telegraf
      port: 8125
      targetPort: 8125
  selector:
    {{- include "homer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
  clusterIP: None
