apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer.fullname" . }}-webapp
  labels:
    {{- include "homer.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  ports:
    - name: homer-webapp
      port: {{ .Values.homerWebApp.service.port }}
      targetPort: 80
  selector:
    {{- include "homer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  type: {{ .Values.homerWebApp.service.type }}
{{- if .Values.homerWebApp.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.homerWebApp.service.loadBalancerIP }}
{{- end }}
